#!/usr/bin/env bash
# configuring the domain and sub domain
disp_subdomain_info () 
{
	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -v rec="$2" 'NR > 1 {print "The subdomain " rec " is a " $4 " record and points to " $5}'
}
if [ "$2" ]
then
    dig_grep_awk "$1" "$2"
else
    disp_subdomain_info "$1" www
    disp_subdomain_info "$1" lb-01
    disp_subdomain_info "$1" web-01
    disp_subdomain_info "$1" web-02
fi
