#!/usr/bin/env bash
# transfers a file from our client to a server using scp

if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

path_tofile="$1"
ip="$2"
username="$3"
path_tossh="$4"

scp -o StrictHostKeyChecking=no -i "$path_tossh" "$path_tofile" "$username@$ip:~/"
