#!/usr/bin/env bash
# A script to configure Nginx server so that /redirect_me is redirecting to another page.
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
