#!/usr/bin/env bash
# Install Nginx and configure to have a custom 404 page
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null
sudo sed -i '/server {/a error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
