#!/usr/bin/env bash
# configuring error 404

# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Configure Nginx to use custom 404 page
sudo sed -i 's/#error_page 404/error_page 404/' /etc/nginx/sites-available/default
sudo sed -i '/error_page 404/a \\t\tlocation = /404.html {\n\t\t\tinternal;\n\t\t}' /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx restart
