#!/usr/bin/env bash
# A script to configure Nginx server so that /redirect_me is redirecting to another page.
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx
# Add custom HTTP header to Nginx
sudo sed -i '/http {/a add_header X-Served-By $hostname;' /etc/nginx/nginx.conf
# Restart Nginx
sudo service nginx restart
