#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

# Install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo bash -c 'cat > /etc/haproxy/haproxy.cfg <<EOF
frontend http-in
  bind *:80
  mode http
  default_backend servers

backend servers
  mode http
  balance roundrobin
  server 49116-web-01 52.91.146.63:80 check
  server 49116-web-02 54.175.25.153:80 check
EOF'

# Enable HAProxy init script
sudo update-rc.d haproxy defaults

# Restart HAProxy service
sudo service haproxy restart
