#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic
sudo apt-get install ufw
sudo ufw allow 22/tcp     # Allow SSH
sudo ufw allow 443/tcp    # Allow HTTPS
sudo ufw allow 80/tcp     # Allow HTTP
sudo ufw deny incoming
sudo ufw enable
sudo ufw status
