#!/usr/bin/env bash
# Define the redirection rule

RULE="*nat\n:PREROUTING ACCEPT [0:0]"
RULE+="\n-A PREROUTING -p tcp --dport 8080"
RULE+=" -j REDIRECT --to-port 80\nCOMMIT\n"

# Backup the current before.rules file
sudo cp /etc/ufw/before.rules /etc/ufw/before.rules.backup

# Add the redirection rule to the top of the before.rules file
echo -e $RULE | cat - /etc/ufw/before.rules > temp
sudo mv temp /etc/ufw/before.rules

# Restart the firewall
sudo ufw disable
sudo ufw enable
