#!/usr/bin/env bash
# Restart Apache web server on Ubuntu 14.04
mkdir apache-docker
cd apache-docker
FROM ubuntu:latest
RUN apt-get update && apt-get install -y apache2
RUN echo "Hello Holberton" > /var/www/html/index.html

EXPOSE 80

CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
docker build -t apache-docker .
docker run -p 8080:80 -d apache-docker
sudo service apache2 restart
