#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080.
# Stop the container if it's already running
docker stop my_nginx > /dev/null 2>&1

# Remove the container if it exists
docker rm my_nginx > /dev/null 2>&1

# Run the container
docker run -d -p 8080:80 --name my_nginx nginx
