#!/usr/bin/env bash
# Configure Nginx to listen on all active IPs on port 8080
sed -i 's/user\s*root;/user nginx;/' /etc/nginx/nginx.conf
sed -i '/listen\s*80;/ a listen 8080;' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
